apiVersion: v1
kind: Service
metadata:
  name: petclicnic
  labels:
    app: petclicnic
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclicnic